generators:
  profile: auto
  profiles:
    solo_doubles:
      base:
        iron:  { interval_ticks: 20,  cap: 48 }
        gold:  { interval_ticks: 100, cap: 16 }
      forge_multipliers:
        0: { iron: 1.0,  gold: 1.0 }
        1: { iron: 1.25, gold: 1.10 }
        2: { iron: 1.50, gold: 1.25 }
        3: { iron: 1.75, gold: 1.40 }
        4: { iron: 2.00, gold: 1.60 }
    trios_quads:
      base:
        iron:  { interval_ticks: 16,  cap: 64 }
        gold:  { interval_ticks: 80,  cap: 24 }
      forge_multipliers:
        0: { iron: 1.0,  gold: 1.0 }
        1: { iron: 1.25, gold: 1.10 }
        2: { iron: 1.50, gold: 1.25 }
        3: { iron: 1.75, gold: 1.40 }
        4: { iron: 2.00, gold: 1.60 }
  team:
    iron:
      interval_ticks: 8
      amount: 1
      cap: 48
    gold:
      interval_ticks: 180
      amount: 1
      cap: 12
    emerald:
      enabled: false
      interval_ticks: 1200
      amount: 1
      cap: 4
  upgrades:
    forge_I:
      gold_interval_multiplier: 0.85
    forge_II:
      gold_interval_multiplier: 0.75
      enable_emerald: true
      emerald_interval_ticks: 900
    forge_III:
      gold_interval_multiplier: 0.65
      emerald_interval_multiplier: 0.75
    molten:
      gold_interval_multiplier: 0.55
      emerald_interval_multiplier: 0.66
  split_generator: true
  auto_collect_radius: 1.2
  spawn_offset_y: 0.5
  diamond:
    tier2_at_seconds: 360
    tier3_at_seconds: 660
  emerald:
    tier2_at_seconds: 420
    tier3_at_seconds: 720
global_tiers:
  diamond:
    tier1_interval_ticks: 600
    tier2_interval_ticks: 400
    tier3_interval_ticks: 300
  emerald:
    tier1_interval_ticks: 1300
    tier2_interval_ticks: 1000
    tier3_interval_ticks: 640
entity_caps:
  team_iron: 48
  team_gold: 12
  team_emerald: 4
  diamond_island: 8
  mid_emerald: 8
drops:
  TEAM_IRON: IRON_INGOT
  TEAM_GOLD: GOLD_INGOT
  TEAM_EMERALD: EMERALD
  DIAMOND: DIAMOND
  EMERALD: EMERALD
holograms:
  enabled: true
  types:
    TEAM_IRON: false
    TEAM_GOLD: false
    DIAMOND: true
    EMERALD: true
  line_1: "&b{type} &7T{tier}"
  line_2: "&f{cooldown}s"
  y_offset: 1.7
paper_tuning:
  merge_radius_item: 2.5
  despawn_ticks: 900
language: fr
debug: false
bounds:
  min_y: -64
  void_kill_y: -60
game:
  min-players: 2
  countdown: 20
  bed-destruction-seconds: 1200
  keep-inventory: false
  auto-assign-on-join: false

countdown:
  chat_milestones: [20, 10, 5, 4, 3, 2, 1]
  actionbar_enabled: true
rules:
  protect-lobby: true
  friendly-fire: false
  break-only-enemy-bed: true
  protect-map: true
  break-only-placed: true
  place-allow:
    - WHITE_WOOL
    - GLASS
    - END_STONE
    - LADDER
    - TNT
  allow-build-states: [RUNNING]

respawn:
  delay_seconds: 5
  clear_drops_on_death: true

kit:
  give_compass_on_spawn: false
  give_blocks_on_spawn: false

armor:
  dye_colored: true

compass:
  opens: rules   # rules | team_selector
  require_permission: false

build:
  allow_all_shop_blocks: true
  extra_allowed_materials: []
  require_permission: false
  bypass_external_protection: true
  worldguard_bypass: false
  wool_all_colors_allowed: true
  track_placed_blocks: true
  no_build:
    npc_radius: 2.0
    gen:
      base_radius: 1.5
      diamond_radius: 1.5
      emerald_radius: 1.5

shop:
  armor_persistent: true

tnt:
  fuse_ticks: 40
  attribute_owner: true

gameplay:
  lock_armor: true
  no_hunger: true

anti_drop:
  swords: true
  leave_item: true
  selector_item: true

tools:
  pickaxe:
    require_sequential: true
    downgrade_on_death: false
    unbreakable: true
    no_drop: true
    tiers:
      1: { material: WOODEN_PICKAXE,  efficiency: 1, price: { IRON: 10 } }
      2: { material: STONE_PICKAXE,   efficiency: 2, price: { IRON: 20 }, requires: 1 }
      3: { material: IRON_PICKAXE,    efficiency: 3, price: { GOLD: 6  }, requires: 2 }
      4: { material: DIAMOND_PICKAXE, efficiency: 4, price: { GOLD: 12 }, requires: 3 }

  axe:
    require_sequential: true
    downgrade_on_death: false
    unbreakable: true
    no_drop: true
    tiers:
      1: { material: WOODEN_AXE,  efficiency: 1, price: { IRON: 10 } }
      2: { material: STONE_AXE,   efficiency: 2, price: { IRON: 20 }, requires: 1 }
      3: { material: IRON_AXE,    efficiency: 3, price: { GOLD: 6  }, requires: 2 }
      4: { material: DIAMOND_AXE, efficiency: 4, price: { GOLD: 12 }, requires: 3 }

fireball:
  enabled: true
  type: BIG        # BIG | SMALL
  speed: 1.2
  explosion_yield: 2.5
  incendiary: false
  break_only_player_blocks: true
  cooldown_ticks: 20

lobby:
  world: world
  x: 0.5
  y: 80.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

items:
  team_selector:
    material: NETHER_STAR
    name: "&bSélecteur d’équipe"
    slot: 0
  leave:
    material: DARK_OAK_DOOR
    name: "&cQuitter l'arène"
    lore:
      - "&7Clique pour retourner au lobby"
    slot: 8
    lock: true

scoreboard:
  enabled: true
  show_next_drop: false
  show_tiers_only: true
actionbar:
  enabled: true

border:
  enabled: true
  center: { x: 0.5, z: 0.5 }
  radius: 120
  warning: 6
  damage:
    enabled: false
    amount: 0.2
    buffer: 2.0
  clamp_y:
    enabled: true
    min: 1
    max: 128
  actions:
    on_cross: "PUSH_BACK"
    push_back_strength: 0.8

reset:
  lobby_world: "world"
  lobby_spawn: { x: 0, y: 100, z: 0, yaw: 0, pitch: 0 }
  templates_path: "plugins/Bedwars/templates"
  runtime_prefix: "bw_"
  atomic_copy: true
  preserve_on_disable: true
  clear_placed_blocks_on_end: true

cleanup:
  blocks_per_tick: 400

lighting:
  force_day: true
  day_time: 6000
  lock_day: true
  clear_weather: true
  relight_on_world_load: true
  waiting_night_vision: false
