generators:
  team:
    iron:
      interval_ticks: 8
      amount: 1
      cap: 48
    gold:
      interval_ticks: 180
      amount: 1
      cap: 12
    emerald:
      enabled: false
      interval_ticks: 1200
      amount: 1
      cap: 4
  upgrades:
    forge_I:
      gold_interval_multiplier: 0.85
    forge_II:
      gold_interval_multiplier: 0.75
      enable_emerald: true
      emerald_interval_ticks: 900
    forge_III:
      gold_interval_multiplier: 0.65
      emerald_interval_multiplier: 0.75
    molten:
      gold_interval_multiplier: 0.55
      emerald_interval_multiplier: 0.66
  split_generator: true
  auto_collect_radius: 1.2
  spawn_offset_y: 0.5
global_tiers:
  diamond:
    tier1_interval_ticks: 600
    tier2_interval_ticks: 400
    tier3_interval_ticks: 300
    announce_times_sec: [300, 540]
  emerald:
    tier1_interval_ticks: 1300
    tier2_interval_ticks: 1000
    tier3_interval_ticks: 640
    announce_times_sec: [420, 780]
entity_caps:
  team_iron: 48
  team_gold: 12
  team_emerald: 4
  diamond_island: 8
  mid_emerald: 8
drops:
  TEAM_IRON: IRON_INGOT
  TEAM_GOLD: GOLD_INGOT
  TEAM_EMERALD: EMERALD
  DIAMOND: DIAMOND
  EMERALD: EMERALD
holograms:
  enabled: true
  types:
    TEAM_IRON: false
    TEAM_GOLD: false
    DIAMOND: true
    EMERALD: true
  line_1: "&b{type} &7T{tier}"
  line_2: "&f{cooldown}s"
  y_offset: 1.7
paper_tuning:
  merge_radius_item: 2.5
  despawn_ticks: 900
language: fr
debug: false
game:
  min-players: 2
  countdown: 20
  void-kill-y: -5
  keep-inventory: false
rules:
  protect-lobby: true
  friendly-fire: false
  break-only-enemy-bed: true
  protect-map: true
  break-only-placed: true
  place-allow: [WHITE_WOOL, GLASS, LADDER, TNT]
  allow-build-states: [RUNNING]

respawn:
  delay_seconds: 5
  clear_drops_on_death: true

kit:
  give_compass_on_spawn: false
  give_blocks_on_spawn: false
