name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.0.1
api-version: '1.21'
author: You
commands:
  bw:
    description: Commandes joueur BedWars
    aliases: [bedwars]
    usage: /bw <join|leave|team|menu>
  bwadmin:
    description: Commandes admin BedWars
    usage: /bwadmin <arena|game|menu>
permissions:
  bedwars.admin:
    description: Accès aux commandes admin BedWars
    default: op
