name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.2.1
api-version: '1.21'
author: You
description: BedWars FR GUI (non-affilié Hypixel)
commands:
  bw:
    description: Menu BedWars + commandes
    usage: /bw
    permission: bedwars.admin
  bwadmin:
    description: Commandes d'administration BedWars
    usage: /bwadmin
    permission: bedwars.admin.arena
permissions:
  bedwars.admin.*:
    description: Toutes les permissions admin
    default: op
    children:
      bedwars.admin: true
      bedwars.admin.arena: true
  bedwars.admin:
    description: Accès au menu de gestion
    default: op
  bedwars.admin.arena:
    description: Gestion des arènes
    default: op
  bedwars.join:
    description: Rejoindre une arène
    default: true
