name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.0.1
api-version: '1.21'
author: You
commands:
  bw:
    description: Commandes joueur BedWars
    aliases: [bedwars]
    usage: /bw <join|leave|team|menu>
  bwadmin:
    description: Commandes admin BedWars
    usage: /bwadmin <arena|game|menu>
permissions:
  bedwars.admin.*:
    description: Tous les droits BedWars
    default: op
    children:
      bedwars.admin.arena: true
      bedwars.admin.team: true
      bedwars.admin.npc: true
      bedwars.admin.gen: true
      bedwars.admin.rules: true
      bedwars.admin.game: true
      bedwars.admin.rotation: true
      bedwars.admin.reset: true
      bedwars.admin.debug: true
      bedwars.admin.maintenance: true
      bedwars.admin.backup: true
  bedwars.menu.rules:
    description: Ouvrir le menu Règles via la boussole
    default: true
  bedwars.build.place:
    description: Poser des blocs whitelistes en arène
    default: true
  bedwars.menu.shop:
    description: Ouvrir la boutique d'objets
    default: true
  bedwars.menu.upgrades:
    description: Ouvrir le menu des améliorations
    default: true
