name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.2.3
api-version: '1.21'
commands:
  bw:
    description: BedWars command
    aliases: [bedwars]
  bwadmin:
    description: BedWars admin command
permissions:
  bedwars.admin.*:
    description: All bedwars admin permissions
    children:
      bedwars.admin.arena: true
      bedwars.admin.team: true
      bedwars.admin.npc: true
      bedwars.admin.gen: true
      bedwars.admin.rules: true
      bedwars.admin.game: true
      bedwars.admin.rotation: true
      bedwars.admin.reset: true
      bedwars.admin.debug: true
      bedwars.admin.maintenance: true
