name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.0.1
api-version: '1.21'
author: You
commands:
  bw:
    description: Commandes joueur BedWars
    usage: /bw <help>
    aliases: [bedwars]
  bwadmin:
    description: Commandes admin BedWars
    usage: /bwadmin <help>
permissions:
  bedwars.admin:
    description: Accès aux commandes admin BedWars
    default: op
  bedwars.admin.*:
    description: Accès à toutes les commandes admin BedWars
    default: op
    children:
      bedwars.admin: true
