name: Bedwars
main: com.example.bedwars.BedwarsPlugin
version: 0.2.1
api-version: '1.21'
author: You
description: BedWars FR GUI (non-affilié Hypixel)
commands:
  bw:
    description: Menu BedWars + commandes
    usage: /bw
permissions:
  bedwars.admin:
    description: Admin BedWars
    default: op
  bedwars.join:
    description: Rejoindre une arène
    default: true
